[package]
name = "rti-search"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rti-core.workspace = true
rti-sim.workspace = true
rti-nn.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
rand.workspace = true
rand_distr.workspace = true
tracing.workspace = true
