//! Mine port-height relations from a map corpus: for every pair of pieces
//! whose ports meet in (x, z) with opposite directions, record the height
//! of the neighbour's base relative to this piece's base. Aggregated per
//! block name and port, this reveals slope rises and surface offsets.
//! `cargo run --release -p rti-maps --example heightmine -- <maps dir>`
use rti_maps::catalog::Catalog;
use std::collections::{BTreeMap, HashMap};

fn main() -> anyhow::Result<()> {
    let dir = std::env::args().nth(1).expect("maps dir");
    let cat = Catalog::default_catalog();
    // name -> port -> list of (neighbour base y - our base y)
    let mut obs: BTreeMap<String, BTreeMap<usize, Vec<f32>>> = BTreeMap::new();
    let mut files: Vec<_> = std::fs::read_dir(&dir)?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.to_string_lossy().ends_with(".Map.Gbx"))
        .collect();
    files.sort();
    for f in files {
        let Ok(m) = std::fs::read(&f)
            .map_err(anyhow::Error::from)
            .and_then(|d| rti_maps::parse_map(&d))
        else {
            continue;
        };
        let pieces = rti_maps::compile::placed_ports(&m, &cat);
        let mut by_pt: HashMap<(i32, i32), Vec<(usize, usize)>> = HashMap::new();
        for (i, (_, _, ports)) in pieces.iter().enumerate() {
            for (k, p) in ports.iter().enumerate() {
                by_pt
                    .entry(((p.0 / 4.0).round() as i32, (p.1 / 4.0).round() as i32))
                    .or_default()
                    .push((i, k));
            }
        }
        for (i, (name, base, ports)) in pieces.iter().enumerate() {
            // only flat 1x1 straights as reference neighbours keep the signal clean
            for (k, p) in ports.iter().enumerate() {
                let Some(v) = by_pt.get(&((p.0 / 4.0).round() as i32, (p.1 / 4.0).round() as i32))
                else {
                    continue;
                };
                for &(j, kk) in v {
                    if j == i {
                        continue;
                    }
                    let (nname, nbase, nports) = &pieces[j];
                    let q = nports[kk];
                    if q.2 * p.2 + q.3 * p.3 > -0.5 {
                        continue;
                    }
                    if !(nname.ends_with("Straight")
                        || nname.ends_with("Base")
                        || nname.ends_with("Checkpoint")
                        || nname.ends_with("Start")
                        || nname.ends_with("Finish"))
                    {
                        continue;
                    }
                    let d = nbase - base;
                    if d.abs() <= 40.0 {
                        obs.entry(name.clone())
                            .or_default()
                            .entry(k)
                            .or_default()
                            .push(d);
                    }
                }
            }
        }
    }
    // machine-readable table: name -> per-port median offsets (ports with < 15 observations are left out)
    if let Some(out) = std::env::args().nth(2) {
        let mut toml = String::from("# Generated by `cargo run -p rti-maps --example heightmine -- <maps dir> <this file>`.\n# Per block name: median height of the neighbouring piece's base relative to this piece's base,\n# at each port (0 = entry/bottom, 1 = exit/top, 2.. = other edges of open pieces).\n\n");
        let mut names: Vec<_> = obs.keys().cloned().collect();
        names.sort();
        for name in names {
            let ports = &obs[&name];
            let mut entries = vec![];
            for (k, v) in ports {
                if v.len() >= 15 {
                    let mut w = v.clone();
                    w.sort_by(|a, b| a.partial_cmp(b).unwrap());
                    entries.push(format!("[{}, {:.1}, {}]", k, w[w.len() / 2], w.len()));
                }
            }
            if !entries.is_empty() {
                toml.push_str(&format!(
                    "[[piece]]\nname = \"{}\"\nports = [{}]\n\n",
                    name.replace('\\', "/"),
                    entries.join(", ")
                ));
            }
        }
        std::fs::write(&out, toml)?;
        eprintln!("wrote {out}");
    }
    println!(
        "{:<48} port  n   median   mean  (neighbour base − own base, m)",
        "block"
    );
    let mut rows: Vec<(String, usize, Vec<f32>)> = vec![];
    for (name, ports) in obs {
        for (k, mut v) in ports {
            v.sort_by(|a, b| a.partial_cmp(b).unwrap());
            rows.push((name.clone(), k, v));
        }
    }
    rows.sort_by(|a, b| b.2.len().cmp(&a.2.len()));
    for (name, k, v) in rows.iter().take(150) {
        let med = v[v.len() / 2];
        let mean = v.iter().sum::<f32>() / v.len() as f32;
        // only print interesting ones: non-zero medians or slope/tilt/platform names
        if med.abs() > 0.5
            || name.contains("Slope")
            || name.contains("Platform")
            || name.starts_with("Deco")
        {
            println!(
                "{:<48} {:>4} {:>4} {:>7.1} {:>6.1}",
                name,
                k,
                v.len(),
                med,
                mean
            );
        }
    }
    Ok(())
}
